#!/usr/bin/env bash
# script that displays numbers from 1 to 100.
#    Displays FizzBuzz when the number is a multiple of 3 and 5
#    Displays Fizz when the number is multiple of 3
#    Displays Buzz when the number is a multiple of 5
#    Otherwise, displays the number
#    In a list format
for (( x=1; x<=100; x++))
do
	if ! (( x % 5 )) && ! (( x % 3 ))
	then
		echo "FizzBuzz"
	elif ! (( x % 5 ))
	then
		echo "Buzz"
	elif ! (( x % 3 ))
	then
		echo "Fizz"
	else
		echo $x
	fi
done
